# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
[tools]
luau-lsp = "JohnnyMorganz/luau-lsp@1.40.0"
selene = "kampfkarren/selene@0.28.0"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.4.2"